
---
- hosts: 100.118.141.31

  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        
    - name: Send webhook to Home Assistant
      uri:
        url: "https://hooks.nabu.casa/gAAAAABknbYBSyYob7aqQvXG6sPjHCVrVjQWHoa8TU8n9AGoyw3jjRzghfdFVEfIiFpEEwFPK5UuDCOPXwAwA08Z2Op9K8f5DI_WjWhTyhRuTAGFTucYFtlbirwEDxXcyTjNt10VlYnh75-GZ6klR69NhVDJEiM2YnS_ZOpp3RErp2h591Gr9v0="
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          message: "Server updates and upgrades completed"
