---
- hosts: 192.168.150.144

  become: yes
  become_method: su
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
